name: Check Kebab Case Naming Convention

on:
  push:
    paths:
      - '**/*'

jobs:
  check-kebab-case:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Modified or Created Files
        run: |
          non_conforming_files=$(git diff --name-only HEAD~1 HEAD | grep -E -v '^[a-z]+(-[a-z]+)*$')
          if [ -n "$non_conforming_files" ]; then
            echo "Files with non-conforming names:"
            echo "$non_conforming_files"
            exit 1
          else
            echo "All modified or created files follow the kebab case convention."
          fi
