name: Shell Check

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev"]
    paths:
      - '**/*.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.sh'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint
        uses: azohra/shell-linter@latest
        with:
          exclude-paths: "LICENSE"
          severity: "error"
